export const en = [
  "Your smile brightens my day.",
  "You always support me, no matter what.",
  "Your kindness is infectious.",
  "I love the way you laugh.",
  "You make me feel safe and loved.",
  "Your intelligence inspires me.",
  "You have a great sense of humor.",
  "Your passion for life is contagious.",
  "I appreciate your honesty.",
  "You are always there for me.",
  "Your creativity knows no bounds.",
  "Your love is my anchor.",
  "I appreciate your willingness to compromise.",
  "Your touch is electric.",
  "Your commitment to personal growth is inspiring.",
  "I love the way you make me feel important.",
  "You are my greatest blessing.",
  "Your positive energy is infectious.",
  "I am grateful for the little things you do.",
  "You are my partner in crime and in life.",
  "Our love has no bounds.",
  "I love the way you make me feel loved and wanted.",
  "You ignite me everytime I see you",
  "You are the Agni of my life",
  "You are my home, you are my world.",
];

export const bn = [
  "তুমি পৃথিবীতে এক টুকরা জান্নাত",
  "তোমার হাসি আলোকিত করে আমায় ",
  "তুমি আমার সবকিছু",
  "আমি তোমাকে নিজের থেকেও বেশি ভালবাসি",
  "তুমি আমার সকালের আলো",
  "তুমি আমার অর্ধাঙ্গিনী",
  "তুমিই আমার বেচে থাকার প্রত্যাশা",
  "তুমি আমার ভবিষ্যৎ ",
  "তুমি আমার হৃদস্পন্দন ",
  "তুমি আমার মহাকর্ষ",
  "তুমি আমার অগ্নি",
  "তুমি আমার সোনাম  এবং আমি তোমার গল্টু",
  "তুমি আমার হৃদয়ের বসন্ত",
  "তোমার চোখে আমি আমার ভবিষ্যৎ দেখি",
  "তুমি আমার ফুলের বাগান ",
  "তোমার ঠোট আমার মধু",
  "আমি আমাদের জন্য আল্লাহ এর কাছে চিরকৃতজ্ঞ",
  "আমি তোমাকে সারাজীবন আগলে রাখতে চাই "
];
